### ISSUE TITLE
confusing grid

### ISSUE THREAD

**Issue by exlo89** [m1a9l9t7e/tronAi#5]
Moin Leute. 
Ich boxe mich gerade son bisschen durch den Code.
Aber wieso habt ihr das Spielfeld Grid Array vertauscht. 
Die X-Achse ist im äußeren Array (als Spalte) und die Y-Achse ist im inneren Array (als Zeile). grid[x][y]
Das bringt mich echt durcheinander :D. 

Damals in Proggen 1 beim Schiffe versenken war das umgekehrt.
grid[y][x] 
Das lief dann auch besser mit der Ausgabe auf dem Terminal. 

Vielleicht denk ich einfach nur verkehrt aber ich hab hier seit 1 2 Stunden Probleme und lasse mich voll verwirren. :D

Können das ja Morgen nochmal bequatschen :*

**Comment by soeiner** [comment]
Naja es ist auch intuitiv, zuerst die x-Koordinate anzugeben, so wie hier. Die Ausgabe auf der Kommandozeile kannst du ja auch andersherum programmieren, dann stimmt es wieder:) 
Außerdem würde ich dir anstatt der Ausgabe auf der Kommandozeile eher den Output auf dem Spielfeld über game.screen.drawPath(arrayList, color) empfehlen.

**Comment by m1a9l9t7e** [comment]
*pos.game.drawPath(ArrayList<int[]> path)
Sven L <notifications@github.com> schrieb am Mi. 1. März 2017 um 09:48:
